### ISSUE TITLE
504 error

### ISSUE THREAD

**Issue by Bonboon229** [Plouni/smash_wav_to_pcm#1]
Scripts unfortunately fail with the dreaded 504 Gateway Error

**Comment by Plouni** [comment]
Thanks for letting me know script was getting that 504 error! I think the website has changed the server and maybe that's the cause? Anyway, I've added a new header when requesting the brstm file and it's working perfectly now! Check out the latest version :)

**Comment by Bonboon229** [comment]
Works like it should now, I made some personal edits to the script to act
as a simple BRSTM downloader. Would you mind if I forked my version of the
script with full credit to you?

**Comment by Plouni** [comment]
No problem do as you wish!

**Comment by Bonboon229** [comment]
Thanks!
